const experiencesData = [
  {
    id: "5",
    company: "Alcyone - Spuerkeess",
    url: "https://alcyone-consulting.lu/",
    title: "Consulting Engineer (.NET)",
    type: "Permanent Contract ",
    summary:
      "As a consultant at Spuerkeess, I was in charge of implementing innovative features and the migration of the whole architecture of the document's processing",
    jobs: [
      "Development of the Mailing Workflow",
      "In charge of the migration of GMC architecture from R12 to R14. +10k documents/day. (Deployed RestAPI, MQ, FTP On Demand workflows)",
      "Development of a Fax Server communication middleware using RightFax.",
    ],
    startDate: "2019-02-15",
    endDate: "Present",
    tags: [
      { id: "5_0", name: "Front-End" },
      { id: "5_1", name: "Software" },
      { id: "5_2", name: ".NET" },
      { id: "5_3", name: "WebServices SOAP" },
      { id: "5_4", name: "RestAPI" },
      { id: "5_5", name: "V-Cycle" },
      { id: "5_6", name: "GMC" },
      { id: "5_7", name: "Bank" },
      { id: "5_8", name: "Swift" },
      { id: "5_9", name: "DB2" },
      { id: "5_10", name: "RightFax" },
    ],
    contact: [
      {
        id: "5_0_0",
        name: "Contact Me",
        title: "CEO",
      },
      {
        id: "5_0_1",
        name: "Contact Me",
        title: "Deputy Head of IT division",
      },
    ],
  },
  {
    id: "0",
    company: "Davidson - Spuerkeess",
    url: "https://www.davidson.fr/",
    title: "Consulting Engineer (.NET)",
    type: "Permanent Contract ",
    summary:
      "As a consultant at Spuerkeess, I was in charge of the development of digital application according to the new policy of the Bank",
    jobs: [
      "Development of a monitoring application for the software called Corona",
      "Development of an internal accounting management.",
      "Creation of documents using GMC Inspire Designer",
      "Development of the Signing Pad Process (Electronic signature)",
      "Development of the Print Workflow",
      "Development of a document injection into the customer bank application",
    ],
    startDate: "2019-02-15",
    endDate: "2021-01-31",
    tags: [
      { id: "0_0", name: "Front-End" },
      { id: "0_1", name: "Software" },
      { id: "0_2", name: ".NET" },
      { id: "0_3", name: "WebServices SOAP" },
      { id: "0_4", name: "RestAPI" },
      { id: "0_5", name: "V-Cycle" },
      { id: "0_6", name: "GMC" },
      { id: "0_7", name: "Bank" },
      { id: "0_8", name: "Swift" },
      { id: "0_9", name: "DB2" },
      { id: "0_10", name: "RightFax" },
    ],
    contact: [
      {
        id: "0_0_0",
        name: "Contact Me",
        title: "Partner",
      },
      {
        id: "0_0_1",
        name: "Contact Me",
        title: "Deputy Head of IT division",
      },
    ],
  },
  {
    id: "1",
    company: "Bouygues",
    title: "Embedded Systems Engineer",
    type: "End of studies Project",
    summary:
      "As an embedded systems engineer, I was in a team of 7 working on a connected tower crane using VR. I was in charge of the Hardware part",
    jobs: [
      "Conception and development of a connected tower crane using VR",
      "Send reliable data from sensors in real time (IO-Link)",
      "Assemble hardware and equipment",
      'Creation of a model, used for the research for the theme "connected construction site"',
    ],
    startDate: "2018-06-01",
    endDate: "2019-01-26",
    tags: [
      { id: "1_1", name: "Synchronous Motor" },
      { id: "1_2", name: "IO-Link" },
      { id: "1_3", name: "Sensors" },
      { id: "1_4", name: "IoT" },
      { id: "1_5", name: "VR" },
      { id: "1_6", name: "AI" },
      { id: "1_7", name: "RFID" },
    ],
    contact: [
      {
        id: "1_0_0",
        name: "Zoubeir Lafhaj",
        title: "Chairman",
      },
    ],
  },
  {
    id: "2",
    company: "Cloudzen",
    url: "https://cloudzen.tech/",
    title: "Software Engineer",
    type: "Internship",
    summary:
      "As a software engineer, I was in charge of the development of a web application and the deployment of a live streaming server",
    jobs: [
      "Development of a web platform of VoD and live streaming",
      "Development of the admin dashboard to manage coupons, games and videos available in the mobile application",
      "Development of a web application for the live streaming",
      "Deployment of 2 Nginx servers for the live streaming. Combine RTMP and RTSP using FFMPEG into Nginx to single HLS adaptive stream",
    ],
    startDate: "2017-11-10",
    endDate: "2018-06-01",
    tags: [
      { id: "2_0", name: "Front-End" },
      { id: "2_1", name: "NodeJS" },
      { id: "2_2", name: "HLS" },
      { id: "2_3", name: "RTMP" },
      { id: "2_4", name: "RTSP" },
      { id: "2_5", name: "NGINX" },
      { id: "2_6", name: "FFMPEG" },
      { id: "2_7", name: "ReactJS" },
      { id: "2_8", name: "Azure" },
      { id: "2_9", name: "Gaming" },
      { id: "2_10", name: "Shell" },
      { id: "2_11", name: "CentOS" },
      { id: "2_12", name: "Scrum" },
      { id: "2_13", name: "SVN" },
      { id: "2_14", name: "Jasmine" },
      { id: "2_15", name: "SCSS" },
    ],
    contact: [
      {
        id: "2_0_0",
        name: "Eugene Lim",
        title: "Senior Lead Engineer",
      },
      {
        id: "2_0_1",
        name: "Robin Tan",
        title: "CEO",
      },
      {
        id: "2_0_2",
        name: "Edmund Shen",
        title: "Creative Director Project Manager",
      },
    ],
  },
  {
    id: "3",
    company: "Everysens",
    url: "https://www.everysens.com",
    title: "Front-End Engineer",
    type: "Internship",
    summary:
      "As a front-end engineer, I was in charge of the development of multiple web applications to track mobile assets via sensors",
    jobs: [
      "Development of a real-time application for mobile assets",
      "Extract data from sensors and display them with reliable and relevant charts or tabs using IoT",
      "Development of specifics features for clients",
      "Development of a managing schedules for drivers and convoys",
    ],
    startDate: "2017-04-03",
    endDate: "2017-11-09",
    tags: [
      { id: "3_0", name: "Front-End" },
      { id: "3_1", name: "AngularJS" },
      { id: "3_2", name: "REST API" },
      { id: "3_3", name: "Leaflet" },
      { id: "3_4", name: "Logistic" },
      { id: "3_5", name: "IoT" },
      { id: "3_6", name: "Sigfox" },
      { id: "3_7", name: "CI/CD" },
      { id: "3_8", name: "Jenkins" },
      { id: "3_9", name: "Bootstrap" },
      { id: "3_10", name: "Scrum" },
    ],
    contact: [
      {
        id: "3_0_0",
        name: "Youness Lembrabet",
        title: "CEO",
      },
      {
        id: "3_0_1",
        name: "Vincent Ollivier",
        title: "Lead Front-End Engineer",
      },
    ],
  },
  {
    id: "4",
    company: "E.I.E",
    url: "http://www.eie.fr",
    title: "Assistant Quality Health and Security Environment Manager",
    type: "Fixed-term Contract",
    summary:
      "As a QHSE Manager, I was in charge to implemented the Environment, Health and Safety programs and policies ",
    jobs: [
      "Ensured the workplace is in full compliance with local Environment, Health and Safety legislation and codes",
      "Conducted accident / incident investigation and ensured all incidents are reported and investigated promptly whereby causes are determined with implementation of corrective actions to prevent recurrence",
      "Facilitated specific quality processes",
    ],
    startDate: "2018-06-15",
    endDate: "2018-08-27",
    tags: [
      { id: "4_0", name: "QHSE" },
      { id: "4_1", name: "Management" },
      { id: "4_2", name: "Legislation" },
      { id: "4_3", name: "ISO Standard" },
      { id: "4_4", name: "Google App Scripts" },
    ],
    contact: [
      {
        id: "4_0_0",
        name: "José de Sousa",
        title: "President",
      },
      {
        id: "4_0_1",
        name: "Annie Maitret",
        title: "QHSE Manager",
      },
    ],
  },
];

export default experiencesData;
